# Deliberately split from the main configuration as the plugins do not use the compose dependency.
Compose:
  CompositionLocalAllowlist:
    active: true
    allowedCompositionLocals: LocalIntegrationPoint,LocalNode
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
  ModifierComposable:
    active: true
  ModifierMissing:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  PreviewNaming:
    active: true
  PreviewPublic:
    active: true
  RememberMissing:
    active: true
