name: Deploy mkdocs to GitHub Pages

on:
  push:
    branches:
      - documentation
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.x'
      - uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4
        with:
          cache-read-only: true
      - run: pip install mkdocs-material
      - run: pip install mkdocs-macros-plugin
      - run: pip install mkdocs-redirects
      - run: pip install mkdocs-include-markdown-plugin
      - run: pip install pillow cairosvg
      - run: mkdocs gh-deploy --force
